bufbuild/protovalidate-python

.github/workflows/release.yaml
step not needed for production use
=> Update release.yaml to remove Publish on TestPyPi

Makefile, protovalidate/internal/constraints.py, protovalidate/internal/extra_func.py, protovalidate/internal/string_format.py, protovalidate/validator.py, pyproject.toml
Despite what `pyproject.toml` says, this project relies on PEP-604 and only works with Python >= 3.10. As a first step, this PR makes that explicit.
Fixes #89.
=> Support only Python 3.11+

README.md
Add documentation for `PYTHONPATH` setting to correct import path errors for generated code.
Fixes #146
=> Document import path for code generation

Makefile, Pipfile, Pipfile.lock, pyproject.toml
`black` is great and mature, but `ruff format` is also great. End of the day, one fewer dependency.
=> Switch from `black` to `ruff format`

.github/workflows/ci.yaml, .github/workflows/conformance.yaml, .github/workflows/release.yaml, pyproject.toml
* Bumps matrices to include 3.13
* Drop matrix from release workflow; use latest to release
* Add individual trove classifiers for each supported version
=> Add explicit Python 3.13 support

protovalidate/internal/constraints.py, protovalidate/validator.py, tests/conformance/runner.py, tests/validate_test.py
Adds the ability to access the captured rule and field value from a `Violation`.
**This is a breaking change.** The API changes in the following ways:
- `ValidationError` has changed:
- Old accesses to `ValidationError.violations` should call `ValidationError.to_proto()` instead, to get a `buf.validate.Violations` message.
- `ValidationError.errors` was removed. Switch to using `ValidationError.violations` instead.
- `ValidationError.violations` provides a list of the new `Violation` wrapper type instead of a list of `buf.validate.Violation`.
-  The new `Violation` wrapper type contains the `buf.validate.Violation` message under the `proto` field, as well as `field_value` and `rule_value` properties that capture the field and rule values, respectively.
- `Validator.collect_violations` now …
=> Add rule and field value to violations

README.md
Matches [`protovalidate-go`'s usage instructions](https://github.com/bufbuild/protovalidate-go?tab=readme-ov-file#usage).
Fixes #229.
=> Fix README cel expression

pyproject.toml
Adds an empty `py.typed` file at the root of the source tree, and adds the [canonical typing classifier][1] to the list of classifiers.
Closes #242.
[1]: https://pypi.org/classifiers/
=> Add PEP 561 type support

protovalidate/internal/extra_func.py
This adds some additional validation for URNs and query strings.
=> Add URN validation

Makefile, protovalidate/internal/string_format.py, tests/conformance/nonconforming.yaml
We can't currently pass the conformance tests involving duration+timestamp types, as cel-python does not support nanoseconds in its duration implementation (linked issue). Otherwise, this gets us to a conformant spot.
Related to #255.
=> Pass `--strict_message` conformance (minus duration/timestamp)

protovalidate/internal/extra_func.py
Here is a proposal for how to structure docstrings in protovalidate-python going forward (at least when porting the rest of the validation implementations). I think this strikes the right balance of adhering to best practices while not being onerous. 
* Functions being added to the library should get the bulk of the comment description in a docstring. No need to define `Args:`, `Raises:`, etc. though.
* Any other public function, class, etc. should preferably have docstrings, though not necessary.
* Be as succinct as possible while also keeping comments across implementations consistently worded.
For validation following an RFC / spec:
* Always include any relevant ABNF grammar and keep aligned.
* Indent grammar inside docstring.
One suggestion outside the scope of this PR might be to …
=> Propose docstring style for repo

protovalidate/internal/extra_func.py
- Avoid ambiguity in "string contains"
- Don't quote identifiers with backticks
- KISS with "Parses the rule"
Context: https://github.com/bufbuild/protovalidate-java/pull/257#discussion_r2028672192
Also see: https://github.com/bufbuild/protovalidate-go/pull/208
=> Fix docstrings in extra_func.py

protovalidate/internal/extra_func.py
`isEmail` incorrectly returns true for the input `foobar@example.com\n`. This happens because `$` will match a line ending even without the multiline flag with [re.match](https://docs.python.org/3/library/re.html#re.match). We need to use [re.fullmatch](https://docs.python.org/3/library/re.html#re.fullmatch) instead.
=> Fix isEmail ignoring trailing newlines

protovalidate/internal/extra_func.py
Same as https://github.com/bufbuild/protovalidate-go/pull/220.
=> Fix isHostAndPort to reject leading zeros in port number

protovalidate/internal/extra_func.py
Same as https://github.com/bufbuild/protovalidate-go/pull/217.
=> Fix IndexError in isUri

protovalidate/internal/extra_func.py, protovalidate/internal/string_format.py, tests/conformance/nonconforming.yaml
We still have the nanosecond granularity issues that we've always had, but this should fix everything else.
=> Fix various v0.11.0 conformance issues

.github/buf-logo.svg
README was showing the old Buf logo. This updates to the new one.
=> Update to new logo

Makefile, buf.yaml, gen/buf/validate/conformance/cases/messages_pb2.py, gen/buf/validate/conformance/cases/messages_pb2.pyi, protovalidate/internal/rules.py
https://github.com/bufbuild/protovalidate/pull/379.
=> Validate `MessageOneofRule`

pyproject.toml
Expression should use a hyphen: https://spdx.org/licenses/
=> Fix license string

test/conformance/runner.py
Seems that `protobuf` no longer segfaults using the dynamic descriptor pool, so we can finish off this TODO.
=> Fix descriptor pool TODO

.github/workflows/release.yaml
I've added a [trusted publisher][1] to our PyPI org. This just completes the process, following the step below.
Ref: https://docs.pypi.org/trusted-publishers/using-a-publisher/#github-actions
[1]: https://docs.pypi.org/trusted-publishers/adding-a-publisher/
=> Set up trusted publishing

README.md
This was removed as a separate workflow in 1f0d1837077765e4c21933202594bddb9f065b5a; now we just have CI.
=> Remove conformance workflow link from README
